services:
  api:
    build: .
    container_name: fundejar_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=fundejar_fundejardb
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=funde2026#$
      - DB_NAME=Dbsurveys
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: fundejar_fundejardb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=funde2026#$
      - POSTGRES_DB=Dbsurveys
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Dbsurveys"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
